/// @file goop.h
/// @brief The entire public surface of goop_native.dll.
///
/// This is the ONLY header a consumer ever sees, and the C# side mirrors it one
/// declaration at a time.
///
/// Every declaration in this header carries a Doxygen `///` comment. That is a
/// house rule, not decoration: this file IS the documentation for anyone
/// binding to the library from another language, and it is the only thing they
/// can read.
///
/// @par ABI rules
/// These are not style preferences. They are load-bearing.
///
/// 1. **C types only.** No C++ in this header: no class, no `std::`, no
///    templates, no references, no default arguments, no overloads. A C#
///    P/Invoke signature has to be able to describe every parameter exactly.
///
/// 2. **No exceptions cross this boundary. Ever.** A C++ exception unwinding
///    into the CLR is undefined behaviour, not an error message. api.cpp wraps
///    every entry point in a catch-all and returns a ::goop_status instead.
///
/// 3. **Fixed-size integer types** from `<stdint.h>` for anything that crosses
///    the boundary. Never `int`, `long`, or `size_t` in a struct field - their
///    widths are a property of the compiler, not of the ABI.
///
/// 4. **Every exported symbol is prefixed `goop_`** - functions, structs, enums
///    and typedefs alike. The DLL shares a global symbol namespace with
///    whatever else the host process has loaded.
///
/// 5. **Output buffers are allocated by the CALLER**, filled by the callee. The
///    pattern is always two calls: ask for the count, allocate, then copy out.
///    goop never hands back a pointer the caller must free, because "which
///    allocator owns this?" is the classic interop crash.
///
/// 6. **Callbacks must not throw and must not unwind.** A progress callback
///    that lets a managed exception escape will tear down the process. The
///    managed side catches inside the delegate; the native side treats the
///    callback as noexcept and only reads its return value.
///
/// 7. **Handles are opaque.** ::goop_shape and ::goop_mesh are incomplete
///    struct types by design: the layout is private, may change freely, and the
///    size is never part of the contract.
///
/// 8. **Struct layout is frozen once shipped.** Fields are appended, never
///    inserted or reordered, and ::GOOP_ABI_VERSION goes up when that promise
///    has to be broken.

#ifndef GOOP_GOOP_H
#define GOOP_GOOP_H

#include "goop_export.h" /* generated by CMake; defines GOOP_API */

#include <stddef.h>
#include <stdint.h>

/// @brief Binary-compatibility version of this ABI.
///
/// Bumped whenever the ABI changes in a way that breaks existing callers.
/// goop_get_version() returns the value compiled into the DLL, so a caller can
/// compare it with the value it was built against. Goop.dll does exactly that
/// before its first native call, and refuses to run on a mismatch.
#define GOOP_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif

/// @brief A point or vector in 3D space. Plain, blittable, POD.
///
/// Double precision throughout: distance fields accumulate error quickly and
/// float grids show it as visible banding near thin features.
///
/// Layout is part of the ABI (rule 8). The managed Vec3 mirrors it exactly, and
/// goop_vec3_size() exists so a test can prove that rather than trust it.
typedef struct goop_vec3 {
    double x;
    double y;
    double z;
} goop_vec3;

/// @brief Returns sizeof(goop_vec3) as the native compiler computed it.
/// @return The size in bytes. Expected to be 24.
GOOP_API int32_t goop_vec3_size(void);

/// @brief Result of every fallible goop_ call.
typedef enum goop_status {
    GOOP_OK = 0,
    GOOP_ERROR_INVALID_ARGUMENT = 1,
    GOOP_ERROR_NULL_HANDLE = 2,
    GOOP_ERROR_OUT_OF_MEMORY = 3,
    GOOP_ERROR_CANCELLED = 4,
    GOOP_ERROR_INTERNAL = 5
} goop_status;

/// @brief Returns the ABI version compiled into this DLL.
/// @return GOOP_ABI_VERSION. Cannot fail, so it returns the value
///         directly, never a status code.
GOOP_API int32_t goop_get_version(void);

/// @brief Opaque handle to a node in the SDF graph. Reference counted.
typedef struct goop_shape goop_shape;

/// @brief Creates a sphere centred at the origin.
/// @param radius Must be greater than zero.
/// @param out_shape Receives the new handle, or NULL on failure. Caller owns
///        one reference and must pass it to goop_shape_release.
/// @return GOOP_OK, or GOOP_ERROR_INVALID_ARGUMENT / GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_sphere(double radius, goop_shape** out_shape);

/// @brief Drops one reference. Destroys the shape when the count reaches zero.
/// @param shape May be NULL, in which case this does nothing.
GOOP_API void goop_shape_release(goop_shape* shape);

/// @brief Adds one reference. Every retain must be paired with one release.
///
/// Only needed by callers that want to hand the same handle to two independent
/// owners. The CSG functions below retain their operands themselves, so a
/// caller combining shapes never has to call this.
///
/// @param shape May be NULL, in which case this does nothing.
/// @note Thread-safe: the count is atomic, so retain and release may be called
///       from different threads (e.g. a .NET finalizer thread).
GOOP_API void goop_shape_retain(goop_shape* shape);

/* ---------------------------------------------------------------------------
 * CSG operators.
 *
 * Ownership, identical for all four:
 *   - The result RETAINS both operands. The caller may release a and b
 *     immediately after the call; the result keeps them alive for as long as
 *     it lives.
 *   - The caller owns ONE reference to the result and must release it.
 *   - On failure *out_shape is set to NULL and nothing is retained.
 *
 * The same operand may be passed as both a and b, and the same shape may be
 * used in any number of expressions: the graph is a DAG, not a tree.
 * ------------------------------------------------------------------------- */

/// @brief Union of two shapes: inside if inside EITHER. Distance = min(a, b).
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if a or b is NULL,
///         GOOP_ERROR_INVALID_ARGUMENT if out_shape is NULL, or
///         GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_union(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief Intersection of two shapes: inside only if inside BOTH.
///        Distance = max(a, b).
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union.
GOOP_API int32_t goop_shape_intersect(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief a minus b: inside a and NOT inside b. Distance = max(a, -b).
///
/// Order matters: goop_shape_subtract(a, b) carves b out of a.
///
/// @param a The shape being cut. Must not be NULL. Retained by the result.
/// @param b The shape doing the cutting. Must not be NULL. Retained by the
///        result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union.
GOOP_API int32_t goop_shape_subtract(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief Smooth union: like goop_shape_union, but the two surfaces blend
///        into each other where they meet instead of forming a sharp crease.
///
/// Uses the polynomial smooth minimum. Within distance k of where the two
/// fields are equal, the result is blended and pulled outward; everywhere else
/// it is exactly min(a, b). Larger k gives a wider, softer join.
///
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param k Blend radius, in the same units as the shapes. Must be > 0.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union, plus GOOP_ERROR_INVALID_ARGUMENT if k is not
///         greater than zero (including NaN).
GOOP_API int32_t goop_shape_smooth_union(goop_shape* a,
                                         goop_shape* b,
                                         double k,
                                         goop_shape** out_shape);

/* ---------------------------------------------------------------------------
 * Evaluation.
 * ------------------------------------------------------------------------- */

/// @brief Signed distance from one point to the shape's surface.
///
/// Negative inside, zero on the surface, positive outside. For many points use
/// goop_shape_eval_batch instead: one call per point pays the P/Invoke
/// transition cost every time.
///
/// @param shape The shape to query. Must not be NULL. Not retained.
/// @param p The query point, passed by value.
/// @param out_distance Receives the distance. Set to NaN on failure, never 0,
///        so an ignored error cannot be mistaken for "on the surface".
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if shape is NULL, or
///         GOOP_ERROR_INVALID_ARGUMENT if out_distance is NULL.
/// @note Thread-safe for concurrent calls on the same shape: evaluation only
///       reads the graph.
GOOP_API int32_t goop_shape_eval(goop_shape* shape, goop_vec3 p, double* out_distance);

/// @brief Message describing the last failure on the calling thread.
/// @return Owned by the DLL. Valid until the next failing call on this
///         thread. Never NULL; empty string if nothing has failed.
GOOP_API const char* goop_last_error_message(void);

/// @brief Signed distance for many points in one call.
/// @param shape Must not be NULL.
/// @param points Caller-owned array of count points. May be NULL only if count == 0.
/// @param out_distances Caller-owned array of count doubles, filled by this call.
///        May be NULL only if count == 0. Pre-filled with NaN, so on failure
///        no slot looks like a real answer.
/// @param count Number of points. Must be >= 0. Zero is a valid no-op.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE, or GOOP_ERROR_INVALID_ARGUMENT.
GOOP_API int32_t goop_shape_eval_batch(goop_shape* shape,
                                       const goop_vec3* points,
                                       double* out_distances,
                                       int64_t count);

/* ---------------------------------------------------------------------------
 * Transforms.
 *
 * Ownership, identical to the CSG operators: the result RETAINS its input, so
 * the caller may release the input immediately; the caller owns one reference
 * to the result; on failure *out_shape is NULL and nothing is retained. The
 * input is never modified - a transform builds a new node that wraps it.
 * ------------------------------------------------------------------------- */

/// @brief Moves a shape by an offset.
///
/// Implemented by moving the query point the opposite way rather than moving
/// any geometry, so it costs one subtraction per evaluation and the result is
/// still an exact distance field.
///
/// @param shape The shape to move. Must not be NULL. Retained by the result.
/// @param offset How far to move it, passed by value. Every component must be
///        finite: NaN or infinity would make every distance NaN.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if shape is NULL,
///         GOOP_ERROR_INVALID_ARGUMENT if out_shape is NULL or offset is not
///         finite, or GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_translate(goop_shape* shape, goop_vec3 offset, goop_shape** out_shape);

/* ---------------------------------------------------------------------------
 * Meshing.
 *
 * goop_shape_to_mesh turns a shape into a triangle mesh. The mesh is a
 * SNAPSHOT: it holds no reference to the shape, so the shape may be released
 * as soon as the mesh exists. Meshes are NOT reference counted - one owner,
 * released once with goop_mesh_release.
 *
 * Reading a mesh follows ABI rule 5 - the caller allocates:
 *   1. ask for the count   (goop_mesh_vertex_count / goop_mesh_triangle_count)
 *   2. allocate a buffer that big
 *   3. copy into it        (goop_mesh_copy_vertices / goop_mesh_copy_indices)
 *
 * Winding: every triangle is counter-clockwise seen from outside the shape, so
 * (v1 - v0) x (v2 - v0) is an outward normal.
 * ------------------------------------------------------------------------- */

/// @brief Opaque handle to a finished triangle mesh. Single owner.
typedef struct goop_mesh goop_mesh;

/// @brief Progress callback for goop_shape_to_mesh.
///
/// Called on the thread that called goop_shape_to_mesh, with a fraction in
/// [0, 1] that only ever increases and ends at exactly 1.
///
/// @param fraction How much of the work is done.
/// @param user_data Whatever the caller passed to goop_shape_to_mesh, untouched.
/// @return 0 to continue, NONZERO to cancel. After a cancel, goop_shape_to_mesh
///         returns GOOP_ERROR_CANCELLED and produces no mesh.
/// @note Must not throw or unwind (ABI rule 6). A C# delegate behind this
///       pointer must catch its own exceptions.
typedef int32_t (*goop_progress_fn)(double fraction, void* user_data);

/// @brief Builds a triangle mesh of a shape's surface using surface nets.
///
/// Samples the distance field on a grid of cubic cells covering the box
/// [bounds_min, bounds_max], padded by one cell on every side. A surface that
/// crosses the box is clipped, leaving a hole: choose bounds that contain the
/// whole shape. Memory grows with the cube of the resolution.
///
/// @param shape The shape to mesh. Must not be NULL. NOT retained: the mesh is
///        an independent snapshot.
/// @param bounds_min Minimum corner of the box to mesh. Must be finite.
/// @param bounds_max Maximum corner. Must be finite and strictly greater than
///        bounds_min on every axis.
/// @param resolution Number of cells along the LONGEST side of the box, 2..512.
/// @param progress Optional. May be NULL.
/// @param user_data Passed back to progress unchanged. May be NULL.
/// @param out_mesh Receives the new mesh, or NULL on failure or cancellation.
///        The caller owns it and must pass it to goop_mesh_release.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if shape is NULL,
///         GOOP_ERROR_INVALID_ARGUMENT for bad bounds or resolution,
///         GOOP_ERROR_CANCELLED if progress asked to stop, or
///         GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_to_mesh(goop_shape* shape,
                                    goop_vec3 bounds_min,
                                    goop_vec3 bounds_max,
                                    int32_t resolution,
                                    goop_progress_fn progress,
                                    void* user_data,
                                    goop_mesh** out_mesh);

/// @brief Number of vertices in the mesh.
/// @param mesh Must not be NULL.
/// @param out_count Receives the count, or 0 on failure.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE, or GOOP_ERROR_INVALID_ARGUMENT if
///         out_count is NULL.
GOOP_API int32_t goop_mesh_vertex_count(const goop_mesh* mesh, int64_t* out_count);

/// @brief Number of triangles in the mesh. The index buffer holds 3 per triangle.
/// @param mesh Must not be NULL.
/// @param out_count Receives the count, or 0 on failure.
/// @return As goop_mesh_vertex_count.
GOOP_API int32_t goop_mesh_triangle_count(const goop_mesh* mesh, int64_t* out_count);

/// @brief Copies every vertex into a buffer the caller allocated.
/// @param mesh Must not be NULL.
/// @param out_vertices Caller-owned buffer. May be NULL only if the mesh has
///        no vertices.
/// @param capacity Number of goop_vec3 the buffer holds. Must be at least the
///        vertex count; this function never writes past it.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE, or GOOP_ERROR_INVALID_ARGUMENT if
///         the buffer is NULL or too small. On failure the buffer is untouched.
GOOP_API int32_t goop_mesh_copy_vertices(const goop_mesh* mesh,
                                         goop_vec3* out_vertices,
                                         int64_t capacity);

/// @brief Copies every triangle's three vertex indices into a caller buffer.
/// @param mesh Must not be NULL.
/// @param out_indices Caller-owned buffer. May be NULL only if the mesh has no
///        triangles.
/// @param capacity Number of uint32_t the buffer holds. Must be at least
///        3 x the triangle count; this function never writes past it.
/// @return As goop_mesh_copy_vertices.
GOOP_API int32_t goop_mesh_copy_indices(const goop_mesh* mesh,
                                        uint32_t* out_indices,
                                        int64_t capacity);

/// @brief Destroys the mesh.
/// @param mesh May be NULL, in which case this does nothing.
GOOP_API void goop_mesh_release(goop_mesh* mesh);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* GOOP_GOOP_H */
