/// @file goop.h
/// @brief The entire public surface of goop.dll.
///
/// This is the ONLY header a consumer ever sees, and the C# side mirrors it one
/// declaration at a time. Everything below the ABI rules is a TODO list;
/// declarations are added as each milestone lands.
///
/// Every declaration in this header carries a Doxygen `///` comment. That is a
/// house rule, not decoration: this file IS the documentation for anyone
/// binding to the library from another language, and it is the only thing they
/// can read.
///
/// @par ABI rules
/// These are not style preferences. They are load-bearing.
///
/// 1. **C types only.** No C++ in this header: no class, no `std::`, no
///    templates, no references, no default arguments, no overloads. A C#
///    P/Invoke signature has to be able to describe every parameter exactly.
///
/// 2. **No exceptions cross this boundary. Ever.** A C++ exception unwinding
///    into the CLR is undefined behaviour, not an error message. api.cpp wraps
///    every entry point in a catch-all and returns a ::goop_status instead.
///
/// 3. **Fixed-size integer types** from `<stdint.h>` for anything that crosses
///    the boundary. Never `int`, `long`, or `size_t` in a struct field - their
///    widths are a property of the compiler, not of the ABI.
///
/// 4. **Every exported symbol is prefixed `goop_`** - functions, structs, enums
///    and typedefs alike. The DLL shares a global symbol namespace with
///    whatever else the host process has loaded.
///
/// 5. **Output buffers are allocated by the CALLER**, filled by the callee. The
///    pattern is always two calls: ask for the count, allocate, then copy out.
///    goop never hands back a pointer the caller must free, because "which
///    allocator owns this?" is the classic interop crash.
///
/// 6. **Callbacks must not throw and must not unwind.** A progress callback
///    that lets a managed exception escape will tear down the process. The
///    managed side catches inside the delegate; the native side treats the
///    callback as noexcept and only reads its return value.
///
/// 7. **Handles are opaque.** ::goop_shape and ::goop_mesh are incomplete
///    struct types by design: the layout is private, may change freely, and the
///    size is never part of the contract.
///
/// 8. **Struct layout is frozen once shipped.** Fields are appended, never
///    inserted or reordered, and ::GOOP_ABI_VERSION goes up when that promise
///    has to be broken.

#ifndef GOOP_GOOP_H
#define GOOP_GOOP_H

#include "goop_export.h" /* generated by CMake; defines GOOP_API */

#include <stddef.h>
#include <stdint.h>

/// @brief Binary-compatibility version of this ABI.
///
/// Bumped whenever the ABI changes in a way that breaks existing callers. The
/// managed side reads goop_get_version() at startup and refuses to run against
/// a DLL it does not recognise - see milestone M9.
#define GOOP_ABI_VERSION 1

#ifdef __cplusplus
extern "C"
{
#endif

    /* -------------------------------------------------------------------------
 * TODO: everything below this line, added milestone by milestone.
 * Each declaration gets its own /// block: @brief, @param for every argument
 * (including which side owns it), @return, and a note on thread safety where
 * it is not obvious.
 * -------------------------------------------------------------------------
 *
 * --- basic value types ---------------------------------------------------
 *
 * TODO: struct goop_vec3 - three doubles (x, y, z), plain and blittable, laid
 *       out so the C# Vec3 struct can be passed by value with no marshalling.
 *       Double precision throughout: distance fields accumulate error fast,
 *       and float grids show it as visible banding near thin features.
 *
 * TODO: enum goop_status - the return type of (almost) every function here.
 *       Needs at minimum: ok, invalid argument, null handle, out of memory,
 *       cancelled (progress callback asked to stop), and an unknown/internal
 *       catch-all for the exception handler in api.cpp. Fixed integer values,
 *       written out explicitly, never renumbered.
 *
 * TODO: goop_get_version - returns GOOP_ABI_VERSION as compiled into the DLL.
 *       The one function whose signature can never change. Start here: it is
 *       the cheapest possible proof that P/Invoke is finding the DLL at all.
 *
 * --- shapes: opaque, reference counted -----------------------------------
 *
 * TODO: typedef struct goop_shape goop_shape; - opaque handle to a node in the
 *       SDF graph. Never dereferenced outside the core.
 *
 * TODO: primitive constructors: goop_shape_sphere, goop_shape_box,
 *       goop_shape_torus, goop_shape_cylinder. Each takes its parameters plus
 *       a goop_shape** out-parameter and returns goop_status.
 *
 * TODO: CSG operators: goop_shape_union, goop_shape_subtract,
 *       goop_shape_intersect, and goop_shape_smooth_union (which takes an
 *       extra blend radius k - the knob that makes shapes melt together).
 *
 * TODO: transforms: goop_shape_translate, goop_shape_rotate, goop_shape_scale,
 *       goop_shape_twist. All of these build a new node that wraps its input;
 *       none of them mutate the input.
 *
 * TODO: goop_shape_retain / goop_shape_release - the ownership story. Nodes
 *       form a DAG, not a tree: the same sphere can appear in two branches of
 *       a CSG expression, so it is reference counted rather than copied.
 *       Combining shapes retains the operands; release drops one count and
 *       destroys at zero, recursively. The C# ShapeSafeHandle is the managed
 *       half of this contract.
 *
 * TODO: goop_shape_eval_batch - points in, distances out, both
 *       caller-allocated: (shape, const goop_vec3* points, double* distances,
 *       count). Batched rather than per-point because a per-point P/Invoke
 *       makes the transition cost dwarf the arithmetic.
 *
 * --- meshing -------------------------------------------------------------
 *
 * TODO: typedef struct goop_mesh goop_mesh; - opaque handle to a finished
 *       triangle mesh. Not reference counted; single owner, released once.
 *
 * TODO: progress callback typedef, something like
 *           typedef int32_t (*goop_progress_fn)(double fraction, void* user_data);
 *       Returning NONZERO means "cancel" and the mesher unwinds cleanly,
 *       returning the cancelled status. The void* user_data travels with it so
 *       the managed side can round-trip a GCHandle instead of using globals.
 *       Must not throw (ABI rule 6).
 *
 * TODO: goop_shape_to_mesh - (shape, resolution, bounds?, progress_fn,
 *       user_data, goop_mesh** out). The progress function and user_data may
 *       both be NULL for a fire-and-forget mesh.
 *
 * TODO: the copy-out quartet (ABI rule 5):
 *           goop_mesh_vertex_count
 *           goop_mesh_triangle_count
 *           goop_mesh_copy_vertices   (caller buffer of goop_vec3)
 *           goop_mesh_copy_indices    (caller buffer of uint32_t, 3 per tri)
 *       Query the count, allocate, then fill. Each copy function takes the
 *       caller's buffer capacity and refuses to write past it.
 *
 * TODO: goop_mesh_release.
 *
 * --- errors --------------------------------------------------------------
 *
 * TODO: goop_last_error_message - returns a const char* describing the last
 *       failure on the CALLING THREAD. Thread-local storage in api.cpp, owned
 *       by the DLL, valid until the next failing call on that thread. The
 *       caller copies it if it wants to keep it, and never frees it.
 */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* GOOP_GOOP_H */
