/// @file goop.h
/// @brief The entire public surface of goop.dll.
///
/// This is the ONLY header a consumer ever sees, and the C# side mirrors it one
/// declaration at a time. Finished declarations sit above the TODO block;
/// the block lists what has not landed yet.
///
/// Every declaration in this header carries a Doxygen `///` comment. That is a
/// house rule, not decoration: this file IS the documentation for anyone
/// binding to the library from another language, and it is the only thing they
/// can read.
///
/// @par ABI rules
/// These are not style preferences. They are load-bearing.
///
/// 1. **C types only.** No C++ in this header: no class, no `std::`, no
///    templates, no references, no default arguments, no overloads. A C#
///    P/Invoke signature has to be able to describe every parameter exactly.
///
/// 2. **No exceptions cross this boundary. Ever.** A C++ exception unwinding
///    into the CLR is undefined behaviour, not an error message. api.cpp wraps
///    every entry point in a catch-all and returns a ::goop_status instead.
///
/// 3. **Fixed-size integer types** from `<stdint.h>` for anything that crosses
///    the boundary. Never `int`, `long`, or `size_t` in a struct field - their
///    widths are a property of the compiler, not of the ABI.
///
/// 4. **Every exported symbol is prefixed `goop_`** - functions, structs, enums
///    and typedefs alike. The DLL shares a global symbol namespace with
///    whatever else the host process has loaded.
///
/// 5. **Output buffers are allocated by the CALLER**, filled by the callee. The
///    pattern is always two calls: ask for the count, allocate, then copy out.
///    goop never hands back a pointer the caller must free, because "which
///    allocator owns this?" is the classic interop crash.
///
/// 6. **Callbacks must not throw and must not unwind.** A progress callback
///    that lets a managed exception escape will tear down the process. The
///    managed side catches inside the delegate; the native side treats the
///    callback as noexcept and only reads its return value.
///
/// 7. **Handles are opaque.** ::goop_shape and ::goop_mesh are incomplete
///    struct types by design: the layout is private, may change freely, and the
///    size is never part of the contract.
///
/// 8. **Struct layout is frozen once shipped.** Fields are appended, never
///    inserted or reordered, and ::GOOP_ABI_VERSION goes up when that promise
///    has to be broken.

#ifndef GOOP_GOOP_H
#define GOOP_GOOP_H

#include "goop_export.h" /* generated by CMake; defines GOOP_API */

#include <stddef.h>
#include <stdint.h>

/// @brief Binary-compatibility version of this ABI.
///
/// Bumped whenever the ABI changes in a way that breaks existing callers. The
/// managed side reads goop_get_version() at startup and refuses to run against
/// a DLL it does not recognise - see milestone M9.
#define GOOP_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif

/// @brief A point or vector in 3D space. Plain, blittable, POD.
///
/// Double precision throughout: distance fields accumulate error quickly and
/// float grids show it as visible banding near thin features.
///
/// Layout is part of the ABI (rule 8). The managed Vec3 mirrors it exactly, and
/// goop_vec3_size() exists so a test can prove that rather than trust it.
typedef struct goop_vec3 {
    double x;
    double y;
    double z;
} goop_vec3;

/// @brief Returns sizeof(goop_vec3) as the native compiler computed it.
/// @return The size in bytes. Expected to be 24.
GOOP_API int32_t goop_vec3_size(void);

/// @brief Result of every fallible goop_ call.
typedef enum goop_status {
    GOOP_OK = 0,
    GOOP_ERROR_INVALID_ARGUMENT = 1,
    GOOP_ERROR_NULL_HANDLE = 2,
    GOOP_ERROR_OUT_OF_MEMORY = 3,
    GOOP_ERROR_CANCELLED = 4,
    GOOP_ERROR_INTERNAL = 5
} goop_status;

/// @brief Returns the ABI version compiled into this DLL.
/// @return GOOP_ABI_VERSION. Cannot fail, so it returns the value
///         directly, never a status code.
GOOP_API int32_t goop_get_version(void);

/// @brief Opaque handle to a node in the SDF graph. Reference counted.
typedef struct goop_shape goop_shape;

/// @brief Creates a sphere centred at the origin.
/// @param radius Must be greater than zero.
/// @param out_shape Receives the new handle, or NULL on failure. Caller owns
///        one reference and must pass it to goop_shape_release.
/// @return GOOP_OK, or GOOP_ERROR_INVALID_ARGUMENT / GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_sphere(double radius, goop_shape** out_shape);

/// @brief Drops one reference. Destroys the shape when the count reaches zero.
/// @param shape May be NULL, in which case this does nothing.
GOOP_API void goop_shape_release(goop_shape* shape);

/// @brief Adds one reference. Every retain must be paired with one release.
///
/// Only needed by callers that want to hand the same handle to two independent
/// owners. The CSG functions below retain their operands themselves, so a
/// caller combining shapes never has to call this.
///
/// @param shape May be NULL, in which case this does nothing.
/// @note Thread-safe: the count is atomic, so retain and release may be called
///       from different threads (e.g. a .NET finalizer thread).
GOOP_API void goop_shape_retain(goop_shape* shape);

/* ---------------------------------------------------------------------------
 * CSG operators.
 *
 * Ownership, identical for all four:
 *   - The result RETAINS both operands. The caller may release a and b
 *     immediately after the call; the result keeps them alive for as long as
 *     it lives.
 *   - The caller owns ONE reference to the result and must release it.
 *   - On failure *out_shape is set to NULL and nothing is retained.
 *
 * The same operand may be passed as both a and b, and the same shape may be
 * used in any number of expressions: the graph is a DAG, not a tree.
 * ------------------------------------------------------------------------- */

/// @brief Union of two shapes: inside if inside EITHER. Distance = min(a, b).
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if a or b is NULL,
///         GOOP_ERROR_INVALID_ARGUMENT if out_shape is NULL, or
///         GOOP_ERROR_OUT_OF_MEMORY.
GOOP_API int32_t goop_shape_union(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief Intersection of two shapes: inside only if inside BOTH.
///        Distance = max(a, b).
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union.
GOOP_API int32_t goop_shape_intersect(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief a minus b: inside a and NOT inside b. Distance = max(a, -b).
///
/// Order matters: goop_shape_subtract(a, b) carves b out of a.
///
/// @param a The shape being cut. Must not be NULL. Retained by the result.
/// @param b The shape doing the cutting. Must not be NULL. Retained by the
///        result.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union.
GOOP_API int32_t goop_shape_subtract(goop_shape* a, goop_shape* b, goop_shape** out_shape);

/// @brief Smooth union: like goop_shape_union, but the two surfaces blend
///        into each other where they meet instead of forming a sharp crease.
///
/// Uses the polynomial smooth minimum. Within distance k of where the two
/// fields are equal, the result is blended and pulled outward; everywhere else
/// it is exactly min(a, b). Larger k gives a wider, softer join.
///
/// @param a First operand. Must not be NULL. Retained by the result.
/// @param b Second operand. Must not be NULL. Retained by the result.
/// @param k Blend radius, in the same units as the shapes. Must be > 0.
/// @param out_shape Receives the new handle, or NULL on failure.
/// @return As goop_shape_union, plus GOOP_ERROR_INVALID_ARGUMENT if k is not
///         greater than zero (including NaN).
GOOP_API int32_t goop_shape_smooth_union(goop_shape* a,
                                         goop_shape* b,
                                         double k,
                                         goop_shape** out_shape);

/* ---------------------------------------------------------------------------
 * Evaluation.
 * ------------------------------------------------------------------------- */

/// @brief Signed distance from one point to the shape's surface.
///
/// Negative inside, zero on the surface, positive outside. For many points use
/// goop_shape_eval_batch (M3) instead: one call per point pays the P/Invoke
/// transition cost every time.
///
/// @param shape The shape to query. Must not be NULL. Not retained.
/// @param p The query point, passed by value.
/// @param out_distance Receives the distance. Set to NaN on failure, never 0,
///        so an ignored error cannot be mistaken for "on the surface".
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE if shape is NULL, or
///         GOOP_ERROR_INVALID_ARGUMENT if out_distance is NULL.
/// @note Thread-safe for concurrent calls on the same shape: evaluation only
///       reads the graph.
GOOP_API int32_t goop_shape_eval(goop_shape* shape, goop_vec3 p, double* out_distance);

/// @brief Message describing the last failure on the calling thread.
/// @return Owned by the DLL. Valid until the next failing call on this
///         thread. Never NULL; empty string if nothing has failed.
GOOP_API const char* goop_last_error_message(void);

/// @brief Signed distance for many points in one call.
/// @param shape Must not be NULL.
/// @param points Caller-owned array of count points. May be NULL only if count == 0.
/// @param out_distances Caller-owned array of count doubles, filled by this call.
///        May be NULL only if count == 0. Pre-filled with NaN, so on failure
///        no slot looks like a real answer.
/// @param count Number of points. Must be >= 0. Zero is a valid no-op.
/// @return GOOP_OK, GOOP_ERROR_NULL_HANDLE, or GOOP_ERROR_INVALID_ARGUMENT.
GOOP_API int32_t goop_shape_eval_batch(goop_shape* shape,
                                       const goop_vec3* points,
                                       double* out_distances,
                                       int64_t count);

/* -------------------------------------------------------------------------
 * TODO: everything below this line, added milestone by milestone.
 * Each declaration gets its own /// block: @brief, @param for every argument
 * (including which side owns it), @return, and a note on thread safety where
 * it is not obvious.
 * -------------------------------------------------------------------------
 *
 * --- shapes: opaque, reference counted -----------------------------------
 *
 * TODO: primitive constructors still to add: goop_shape_box,
 *       goop_shape_torus, goop_shape_cylinder. Each takes its parameters plus
 *       a goop_shape** out-parameter and returns goop_status.
 *       goop_shape_sphere is already declared above.
 *
 * TODO: transforms: goop_shape_translate, goop_shape_rotate, goop_shape_scale,
 *       goop_shape_twist. All of these build a new node that wraps its input
 *       (and retains it, like the CSG operators); none of them mutate it.
 *
 * --- meshing -------------------------------------------------------------
 *
 * TODO: typedef struct goop_mesh goop_mesh; - opaque handle to a finished
 *       triangle mesh. Not reference counted; single owner, released once.
 *
 * TODO: progress callback typedef, something like
 *           typedef int32_t (*goop_progress_fn)(double fraction, void* user_data);
 *       Returning NONZERO means "cancel" and the mesher unwinds cleanly,
 *       returning the cancelled status. The void* user_data travels with it so
 *       the managed side can round-trip a GCHandle instead of using globals.
 *       Must not throw (ABI rule 6).
 *
 * TODO: goop_shape_to_mesh - (shape, resolution, bounds?, progress_fn,
 *       user_data, goop_mesh** out). The progress function and user_data may
 *       both be NULL for a fire-and-forget mesh.
 *
 * TODO: the copy-out quartet (ABI rule 5):
 *           goop_mesh_vertex_count
 *           goop_mesh_triangle_count
 *           goop_mesh_copy_vertices   (caller buffer of goop_vec3)
 *           goop_mesh_copy_indices    (caller buffer of uint32_t, 3 per tri)
 *       Query the count, allocate, then fill. Each copy function takes the
 *       caller's buffer capacity and refuses to write past it.
 *
 * TODO: goop_mesh_release.
 */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* GOOP_GOOP_H */
